### ISSUE TITLE
Api 接口文档有没有？分析数据很费劲的。。。

### ISSUE THREAD

**Issue by XiFanYin** [git-xuhao/KotlinMvp#14]
@git-xuhao 接口文档有没有？

**Comment by XiFanYin** [comment]
@git-xuhao  还有你的数据类是一个一个写出来的吗？有没有动态生成数据类的插件，推荐一个

**Comment by git-xuhao** [comment]
@XiFanYin 爬 第三方的 api 都需要自己来分析的，分析数据确实费劲 json 生成实体类插件：[https://github.com/wuseal/JsonToKotlinClass](url)
