### ISSUE TITLE
有空帮我定制？

### ISSUE THREAD

**Issue by xfyisheng** [git-xuhao/KotlinMvp#16]
有空帮我定制？31831809@qq.com

**Comment by git-xuhao** [comment]
？

**Comment by xfyisheng** [comment]
给个联系方式可以？


发送自我的三星盖乐世智能手机。
-------- 原始信息 --------由： XuHao <notifications@github.com> 日期: 2018/6/4  09:10  (GMT+08:00) 收件人： git-xuhao/KotlinMvp <KotlinMvp@noreply.github.com> 抄送： xfyisheng <438138313@qq.com>, Author <author@noreply.github.com> 主题： Re: [git-xuhao/KotlinMvp] 有空帮我定制？ (#16) 
？

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/git-xuhao/KotlinMvp/issues/16#issuecomment-394209278","url":"https://github.com/git-xuhao/KotlinMvp/issues/16#issuecomment-394209278","name":"View Issue"},"description":"View this Issue on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/git-xuhao/KotlinMvp","title":"git-xuhao/KotlinMvp","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/git-xuhao/KotlinMvp"}},"updates":{"snippets":[{"icon":"PERSON","message":"@git-xuhao in #16: ？"}],"action":{"name":"View Issue","url":"https://github.com/git-xuhao/KotlinMvp/issues/16#issuecomment-394209278"}}}
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "37567f93-e2a7-4e2a-ad37-a9160fc62647",
"title": "Re: [git-xuhao/KotlinMvp] 有空帮我定制？ (#16)",
"sections": [
{
"text": "",
"activityTitle": "**XuHao**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@git-xuhao",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"git-xuhao/KotlinMvp\",\n\"issueId\": 16,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"git-xuhao/KotlinMvp\",\n\"issueId\": 16\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/git-xuhao/KotlinMvp/issues/16#issuecomment-394209278"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 341869243\n}"
}
],
"themeColor": "26292E"
}
