### ISSUE TITLE
安装后出现内存泄漏的图标!

### ISSUE THREAD

**Issue by gonefuture** [git-xuhao/KotlinMvp#17]
请问内存泄漏的地方在哪里?那个multiple-status-view有什么用啊?

**Comment by gonefuture** [comment]
安装后出现 一个带感叹号的图标,下面显示Leaks.

**Comment by git-xuhao** [comment]
@gonefuture  多种状态的 View，有些内存泄漏是系统级别的

**Comment by gonefuture** [comment]
@git-xuhao  请问你知道大概是那个View出问题了吗？
