### ISSUE TITLE
下载Apk推荐

### ISSUE THREAD

**Issue by Sum-sdl** [git-xuhao/KotlinMvp#19]
你可以自己把apk打包好了放在项目的目录下，一同上传的GitHub，即可通过访问GitHub下载文件。然后讲地址保存下来，放到MD文件中即可。

**Comment by git-xuhao** [comment]
@Sum-sdl  谢谢建议，不过期初我是按照你说的那种方式，后来到改成fir.im。。这个都没啥影响吧
