### ISSUE TITLE
关于Preference类

### ISSUE THREAD

**Issue by skypfan** [git-xuhao/KotlinMvp#21]
对SharedPreferences等封装通过委托机制来实现没有问题，但是类中关于其他的方法，例如clearPreference等，只能先通过委托来获取Preference对象实例，才能调用这些方法，这是有问题的，最直接是将这些方法用companion object包裹

**Comment by git-xuhao** [comment]
@skypfan 嗯，当时写的时候主要关注的是功能方面，工具类这样的是直接转的 kotlin 然后作了小修改，后面我在找个时间把大家的建议统一优化下，谢谢~
