### ISSUE TITLE
你封装的mvp，没有bean基类和统一处理基类错误码

### ISSUE THREAD

**Issue by zhjun2016** [git-xuhao/KotlinMvp#23]
请问您能改进一下，对基类BaseBean继承封装，和对基类错误码进行统一处理码，以及对统一解析bean

**Comment by zhjun2016** [comment]
以及对baseUrl动态改变

**Comment by git-xuhao** [comment]
@zhjun2016 基类 BaseBean 需要怎么封装？基类错误码指的是 API 错误码吗？这个需要和后台沟通定义的，统一解析 Bean，BaseResponse 这个不就是服务器返回响应的基类吗？BaseUrl 动态改变，可以自行添加拦截器实现，这是个开源项目，仅供参考学习，不是框架呢

**Comment by JessYanCoding** [comment]
@zhjun2016 关于动态改变 BaseUrl，可以使用 [RetrofitUrlManager](
https://github.com/JessYanCoding/RetrofitUrlManager/blob/master/README-zh.md) 随意切换任何复杂的 BaseUrl, 正如作者所说，关于错误码之类涉及到服务器和业务，所以不可能封装，而且这也是学习项目不是框架，如果你在寻找一个好用的 MVP 框架的话，可以试试 [MVPArms](
https://github.com/JessYanCoding/MVPArms/wiki)，里面有对服务器错误以及使用 Rxjava 遇到的错误进行集中反馈的功能
