### ISSUE TITLE
一个空指针异常  

### ISSUE THREAD

**Issue by hanouba** [git-xuhao/KotlinMvp#30]
tab_layout.setTabData(mTabEntities)

在app启动的时候 mainactivity界面的 在initTab时  tab_layout.setTabData(mTabEntities) 报空指针；customIntent    = null

**Comment by git-xuhao** [comment]
@hanouba  在什么情况下或者什么操作出现的？一直也没出现这个空指针，麻烦帮忙排查下是否有其他原因导致的，谢谢~

**Comment by hanouba** [comment]
getlayout 没有写在前面 导致的
