### ISSUE TITLE
更换BaseResponse类后，数据解析异常

### ISSUE THREAD

**Issue by jinlinupup** [git-xuhao/KotlinMvp#9]
跟后台确定是这样的形式：
class BaseResponse<T>(val success :Boolean,
                      val obj:T,
                      val msg:String)

运行时报解析数据异常。请问该如何解决呢？谢谢。

**Comment by git-xuhao** [comment]
什么错?

**Comment by jinlinupup** [comment]
不好意思哈，是我这边后台给的数据原因，数据类型解析错误，我跟后台没对好。谢谢你啦。
